# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
  def setupUi(self, MainWindow):
    MainWindow.setObjectName("MainWindow")
    MainWindow.resize(1008, 728)
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap(":/icons/icons/GnuplotEditor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    MainWindow.setWindowIcon(icon)
    self.centralwidget = QtWidgets.QWidget(MainWindow)
    self.centralwidget.setObjectName("centralwidget")
    self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
    self.verticalLayout_4.setObjectName("verticalLayout_4")
    self.verticalLayout = QtWidgets.QVBoxLayout()
    self.verticalLayout.setObjectName("verticalLayout")
    self.editor = Qsci.QsciScintilla(self.centralwidget)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(1)
    sizePolicy.setVerticalStretch(1)
    sizePolicy.setHeightForWidth(self.editor.sizePolicy().hasHeightForWidth())
    self.editor.setSizePolicy(sizePolicy)
    self.editor.setToolTip("")
    self.editor.setWhatsThis("")
    self.editor.setObjectName("editor")
    self.verticalLayout.addWidget(self.editor)
    self.horizontalLayout = QtWidgets.QHBoxLayout()
    self.horizontalLayout.setObjectName("horizontalLayout")
    self.autoPreview = QtWidgets.QCheckBox(self.centralwidget)
    self.autoPreview.setChecked(False)
    self.autoPreview.setObjectName("autoPreview")
    self.horizontalLayout.addWidget(self.autoPreview)
    spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout.addItem(spacerItem)
    self.label_3 = QtWidgets.QLabel(self.centralwidget)
    self.label_3.setObjectName("label_3")
    self.horizontalLayout.addWidget(self.label_3)
    self.encoding = QtWidgets.QComboBox(self.centralwidget)
    self.encoding.setMinimumSize(QtCore.QSize(110, 0))
    self.encoding.setObjectName("encoding")
    self.encoding.addItem("")
    self.encoding.addItem("")
    self.encoding.addItem("")
    self.encoding.addItem("")
    self.encoding.addItem("")
    self.encoding.addItem("")
    self.encoding.addItem("")
    self.encoding.addItem("")
    self.encoding.addItem("")
    self.encoding.addItem("")
    self.encoding.addItem("")
    self.encoding.addItem("")
    self.horizontalLayout.addWidget(self.encoding)
    self.verticalLayout.addLayout(self.horizontalLayout)
    self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_3.setObjectName("horizontalLayout_3")
    spacerItem1 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_3.addItem(spacerItem1)
    self.label_4 = QtWidgets.QLabel(self.centralwidget)
    self.label_4.setObjectName("label_4")
    self.horizontalLayout_3.addWidget(self.label_4)
    self.applySize = QtWidgets.QCheckBox(self.centralwidget)
    self.applySize.setChecked(True)
    self.applySize.setObjectName("applySize")
    self.horizontalLayout_3.addWidget(self.applySize)
    self.sizeMultiply = QtWidgets.QComboBox(self.centralwidget)
    self.sizeMultiply.setMinimumSize(QtCore.QSize(49, 0))
    self.sizeMultiply.setMaximumSize(QtCore.QSize(46, 16777215))
    self.sizeMultiply.setObjectName("sizeMultiply")
    self.sizeMultiply.addItem("")
    self.sizeMultiply.addItem("")
    self.sizeMultiply.addItem("")
    self.horizontalLayout_3.addWidget(self.sizeMultiply)
    self.applyFont = QtWidgets.QCheckBox(self.centralwidget)
    self.applyFont.setChecked(True)
    self.applyFont.setObjectName("applyFont")
    self.horizontalLayout_3.addWidget(self.applyFont)
    spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_3.addItem(spacerItem2)
    self.plotImage = QtWidgets.QPushButton(self.centralwidget)
    self.plotImage.setObjectName("plotImage")
    self.horizontalLayout_3.addWidget(self.plotImage)
    self.verticalLayout.addLayout(self.horizontalLayout_3)
    self.verticalLayout_4.addLayout(self.verticalLayout)
    MainWindow.setCentralWidget(self.centralwidget)
    self.menubar = QtWidgets.QMenuBar(MainWindow)
    self.menubar.setGeometry(QtCore.QRect(0, 0, 1008, 29))
    self.menubar.setObjectName("menubar")
    self.menuFile = QtWidgets.QMenu(self.menubar)
    self.menuFile.setObjectName("menuFile")
    self.menuEdit = QtWidgets.QMenu(self.menubar)
    self.menuEdit.setObjectName("menuEdit")
    self.menuHelp = QtWidgets.QMenu(self.menubar)
    self.menuHelp.setObjectName("menuHelp")
    self.menuCommands = QtWidgets.QMenu(self.menubar)
    self.menuCommands.setObjectName("menuCommands")
    self.menuSet = QtWidgets.QMenu(self.menubar)
    self.menuSet.setObjectName("menuSet")
    self.menuPalette = QtWidgets.QMenu(self.menubar)
    self.menuPalette.setObjectName("menuPalette")
    self.menuCode = QtWidgets.QMenu(self.menubar)
    self.menuCode.setObjectName("menuCode")
    MainWindow.setMenuBar(self.menubar)
    self.toolBar = QtWidgets.QToolBar(MainWindow)
    self.toolBar.setMovable(False)
    self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
    self.toolBar.setFloatable(False)
    self.toolBar.setObjectName("toolBar")
    MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
    self.dockWidget = QtWidgets.QDockWidget(MainWindow)
    self.dockWidget.setObjectName("dockWidget")
    self.dockWidgetContents = QtWidgets.QWidget()
    self.dockWidgetContents.setObjectName("dockWidgetContents")
    self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
    self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
    self.verticalLayout_8.setObjectName("verticalLayout_8")
    self.gnuplotOutput = QtWidgets.QTextBrowser(self.dockWidgetContents)
    self.gnuplotOutput.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 75 bold 9pt \"mono\";\n"
"")
    self.gnuplotOutput.setObjectName("gnuplotOutput")
    self.verticalLayout_8.addWidget(self.gnuplotOutput)
    self.dockWidget.setWidget(self.dockWidgetContents)
    MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget)
    self.dockWidget_2 = QtWidgets.QDockWidget(MainWindow)
    self.dockWidget_2.setObjectName("dockWidget_2")
    self.dockWidgetContents_2 = QtWidgets.QWidget()
    self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
    self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
    self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
    self.verticalLayout_9.setObjectName("verticalLayout_9")
    self.gnuplotInput = QtWidgets.QTextBrowser(self.dockWidgetContents_2)
    self.gnuplotInput.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 75 bold 9pt \"mono\";\n"
"")
    self.gnuplotInput.setObjectName("gnuplotInput")
    self.verticalLayout_9.addWidget(self.gnuplotInput)
    self.dockWidget_2.setWidget(self.dockWidgetContents_2)
    MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_2)
    self.dockWidget_3 = QtWidgets.QDockWidget(MainWindow)
    self.dockWidget_3.setObjectName("dockWidget_3")
    self.dockWidgetContents_3 = QtWidgets.QWidget()
    self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
    self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.dockWidgetContents_3)
    self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
    self.verticalLayout_5.setObjectName("verticalLayout_5")
    self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_4.setObjectName("horizontalLayout_4")
    self.label_5 = QtWidgets.QLabel(self.dockWidgetContents_3)
    self.label_5.setObjectName("label_5")
    self.horizontalLayout_4.addWidget(self.label_5)
    self.filterEntry = QtWidgets.QLineEdit(self.dockWidgetContents_3)
    self.filterEntry.setObjectName("filterEntry")
    self.horizontalLayout_4.addWidget(self.filterEntry)
    self.verticalLayout_5.addLayout(self.horizontalLayout_4)
    self.filenameList = DirListWidget(self.dockWidgetContents_3)
    self.filenameList.setObjectName("filenameList")
    self.verticalLayout_5.addWidget(self.filenameList)
    self.dockWidget_3.setWidget(self.dockWidgetContents_3)
    MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_3)
    self.dockWidget_4 = QtWidgets.QDockWidget(MainWindow)
    self.dockWidget_4.setObjectName("dockWidget_4")
    self.dockWidgetContents_4 = QtWidgets.QWidget()
    self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
    self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents_4)
    self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
    self.verticalLayout_3.setObjectName("verticalLayout_3")
    self.gnuplotImageScroller = QtWidgets.QScrollArea(self.dockWidgetContents_4)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(1)
    sizePolicy.setVerticalStretch(1)
    sizePolicy.setHeightForWidth(self.gnuplotImageScroller.sizePolicy().hasHeightForWidth())
    self.gnuplotImageScroller.setSizePolicy(sizePolicy)
    self.gnuplotImageScroller.setWidgetResizable(True)
    self.gnuplotImageScroller.setObjectName("gnuplotImageScroller")
    self.gnuplotImageHolder = QtWidgets.QWidget()
    self.gnuplotImageHolder.setGeometry(QtCore.QRect(0, 0, 285, 296))
    self.gnuplotImageHolder.setObjectName("gnuplotImageHolder")
    self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gnuplotImageHolder)
    self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
    self.verticalLayout_2.setObjectName("verticalLayout_2")
    self.gnuplotImageScroller.setWidget(self.gnuplotImageHolder)
    self.verticalLayout_3.addWidget(self.gnuplotImageScroller)
    self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_2.setObjectName("horizontalLayout_2")
    self.fileName = QtWidgets.QLineEdit(self.dockWidgetContents_4)
    self.fileName.setReadOnly(True)
    self.fileName.setObjectName("fileName")
    self.horizontalLayout_2.addWidget(self.fileName)
    self.label_2 = QtWidgets.QLabel(self.dockWidgetContents_4)
    self.label_2.setObjectName("label_2")
    self.horizontalLayout_2.addWidget(self.label_2)
    self.scaling = QtWidgets.QLineEdit(self.dockWidgetContents_4)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.scaling.sizePolicy().hasHeightForWidth())
    self.scaling.setSizePolicy(sizePolicy)
    self.scaling.setMaximumSize(QtCore.QSize(40, 16777215))
    self.scaling.setMaxLength(8)
    self.scaling.setObjectName("scaling")
    self.horizontalLayout_2.addWidget(self.scaling)
    self.label = QtWidgets.QLabel(self.dockWidgetContents_4)
    self.label.setObjectName("label")
    self.horizontalLayout_2.addWidget(self.label)
    self.scaleToFit = QtWidgets.QCheckBox(self.dockWidgetContents_4)
    self.scaleToFit.setChecked(True)
    self.scaleToFit.setObjectName("scaleToFit")
    self.horizontalLayout_2.addWidget(self.scaleToFit)
    self.verticalLayout_3.addLayout(self.horizontalLayout_2)
    self.dockWidget_4.setWidget(self.dockWidgetContents_4)
    MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_4)
    self.actionOpen = QtWidgets.QAction(MainWindow)
    icon1 = QtGui.QIcon()
    icon1.addPixmap(QtGui.QPixmap(":/icons/icons/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionOpen.setIcon(icon1)
    self.actionOpen.setObjectName("actionOpen")
    self.actionSave = QtWidgets.QAction(MainWindow)
    icon2 = QtGui.QIcon()
    icon2.addPixmap(QtGui.QPixmap(":/icons/icons/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionSave.setIcon(icon2)
    self.actionSave.setObjectName("actionSave")
    self.actionSave_As = QtWidgets.QAction(MainWindow)
    icon3 = QtGui.QIcon()
    icon3.addPixmap(QtGui.QPixmap(":/icons/icons/document-save-as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionSave_As.setIcon(icon3)
    self.actionSave_As.setObjectName("actionSave_As")
    self.actionCopy = QtWidgets.QAction(MainWindow)
    icon4 = QtGui.QIcon()
    icon4.addPixmap(QtGui.QPixmap(":/icons/icons/edit-copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionCopy.setIcon(icon4)
    self.actionCopy.setObjectName("actionCopy")
    self.actionCut = QtWidgets.QAction(MainWindow)
    icon5 = QtGui.QIcon()
    icon5.addPixmap(QtGui.QPixmap(":/icons/icons/edit-cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionCut.setIcon(icon5)
    self.actionCut.setObjectName("actionCut")
    self.actionPaste = QtWidgets.QAction(MainWindow)
    icon6 = QtGui.QIcon()
    icon6.addPixmap(QtGui.QPixmap(":/icons/icons/edit-paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionPaste.setIcon(icon6)
    self.actionPaste.setObjectName("actionPaste")
    self.actionComment = QtWidgets.QAction(MainWindow)
    icon7 = QtGui.QIcon()
    icon7.addPixmap(QtGui.QPixmap(":/icons/icons/comment.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionComment.setIcon(icon7)
    self.actionComment.setObjectName("actionComment")
    self.actionUncomment = QtWidgets.QAction(MainWindow)
    icon8 = QtGui.QIcon()
    icon8.addPixmap(QtGui.QPixmap(":/icons/icons/uncomment.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionUncomment.setIcon(icon8)
    self.actionUncomment.setObjectName("actionUncomment")
    self.actionPaste_Color = QtWidgets.QAction(MainWindow)
    icon9 = QtGui.QIcon()
    icon9.addPixmap(QtGui.QPixmap(":/icons/icons/preferences-desktop-color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionPaste_Color.setIcon(icon9)
    self.actionPaste_Color.setObjectName("actionPaste_Color")
    self.actionIgnore = QtWidgets.QAction(MainWindow)
    icon10 = QtGui.QIcon()
    icon10.addPixmap(QtGui.QPixmap(":/icons/icons/ignore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionIgnore.setIcon(icon10)
    self.actionIgnore.setObjectName("actionIgnore")
    self.actionUnignore = QtWidgets.QAction(MainWindow)
    icon11 = QtGui.QIcon()
    icon11.addPixmap(QtGui.QPixmap(":/icons/icons/unignore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionUnignore.setIcon(icon11)
    self.actionUnignore.setObjectName("actionUnignore")
    self.actionPreview = QtWidgets.QAction(MainWindow)
    icon12 = QtGui.QIcon()
    icon12.addPixmap(QtGui.QPixmap(":/icons/icons/run_preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionPreview.setIcon(icon12)
    self.actionPreview.setObjectName("actionPreview")
    self.actionRun_Normal = QtWidgets.QAction(MainWindow)
    icon13 = QtGui.QIcon()
    icon13.addPixmap(QtGui.QPixmap(":/icons/icons/run_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionRun_Normal.setIcon(icon13)
    self.actionRun_Normal.setObjectName("actionRun_Normal")
    self.actionUndo = QtWidgets.QAction(MainWindow)
    icon14 = QtGui.QIcon()
    icon14.addPixmap(QtGui.QPixmap(":/icons/icons/edit-undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionUndo.setIcon(icon14)
    self.actionUndo.setObjectName("actionUndo")
    self.actionRedo = QtWidgets.QAction(MainWindow)
    icon15 = QtGui.QIcon()
    icon15.addPixmap(QtGui.QPixmap(":/icons/icons/edit-redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionRedo.setIcon(icon15)
    self.actionRedo.setObjectName("actionRedo")
    self.actionNew = QtWidgets.QAction(MainWindow)
    icon16 = QtGui.QIcon()
    icon16.addPixmap(QtGui.QPixmap(":/icons/icons/document-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionNew.setIcon(icon16)
    self.actionNew.setObjectName("actionNew")
    self.actionPick_Position = QtWidgets.QAction(MainWindow)
    icon17 = QtGui.QIcon()
    icon17.addPixmap(QtGui.QPixmap(":/icons/icons/pick_position.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionPick_Position.setIcon(icon17)
    self.actionPick_Position.setObjectName("actionPick_Position")
    self.actionGnuplot_Help = QtWidgets.QAction(MainWindow)
    self.actionGnuplot_Help.setObjectName("actionGnuplot_Help")
    self.actionAbout = QtWidgets.QAction(MainWindow)
    self.actionAbout.setObjectName("actionAbout")
    self.actionAdd_Line_at_Cursor = QtWidgets.QAction(MainWindow)
    self.actionAdd_Line_at_Cursor.setObjectName("actionAdd_Line_at_Cursor")
    self.actionDeleteMacro = QtWidgets.QAction(MainWindow)
    self.actionDeleteMacro.setObjectName("actionDeleteMacro")
    self.actionInset_Template = QtWidgets.QAction(MainWindow)
    icon18 = QtGui.QIcon()
    icon18.addPixmap(QtGui.QPixmap(":/icons/icons/insert-text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionInset_Template.setIcon(icon18)
    self.actionInset_Template.setObjectName("actionInset_Template")
    self.actionQuit = QtWidgets.QAction(MainWindow)
    icon19 = QtGui.QIcon()
    icon19.addPixmap(QtGui.QPixmap(":/icons/icons/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionQuit.setIcon(icon19)
    self.actionQuit.setObjectName("actionQuit")
    self.actionFind_Replace = QtWidgets.QAction(MainWindow)
    icon20 = QtGui.QIcon()
    icon20.addPixmap(QtGui.QPixmap(":/icons/icons/edit-find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionFind_Replace.setIcon(icon20)
    self.actionFind_Replace.setObjectName("actionFind_Replace")
    self.actionWrap_Lines = QtWidgets.QAction(MainWindow)
    self.actionWrap_Lines.setCheckable(True)
    self.actionWrap_Lines.setChecked(True)
    self.actionWrap_Lines.setObjectName("actionWrap_Lines")
    self.actionPrint = QtWidgets.QAction(MainWindow)
    icon21 = QtGui.QIcon()
    icon21.addPixmap(QtGui.QPixmap(":/icons/icons/document-print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.actionPrint.setIcon(icon21)
    self.actionPrint.setObjectName("actionPrint")
    self.menuFile.addAction(self.actionNew)
    self.menuFile.addSeparator()
    self.menuFile.addAction(self.actionOpen)
    self.menuFile.addSeparator()
    self.menuFile.addAction(self.actionSave)
    self.menuFile.addAction(self.actionSave_As)
    self.menuFile.addSeparator()
    self.menuFile.addAction(self.actionWrap_Lines)
    self.menuFile.addSeparator()
    self.menuFile.addAction(self.actionPrint)
    self.menuFile.addSeparator()
    self.menuFile.addAction(self.actionQuit)
    self.menuEdit.addAction(self.actionUndo)
    self.menuEdit.addAction(self.actionRedo)
    self.menuEdit.addSeparator()
    self.menuEdit.addAction(self.actionCopy)
    self.menuEdit.addAction(self.actionCut)
    self.menuEdit.addAction(self.actionPaste)
    self.menuEdit.addSeparator()
    self.menuEdit.addAction(self.actionFind_Replace)
    self.menuHelp.addAction(self.actionGnuplot_Help)
    self.menuHelp.addAction(self.actionAbout)
    self.menuCommands.addAction(self.actionAdd_Line_at_Cursor)
    self.menuCommands.addAction(self.actionDeleteMacro)
    self.menuCommands.addSeparator()
    self.menuCode.addAction(self.actionPreview)
    self.menuCode.addAction(self.actionRun_Normal)
    self.menuCode.addSeparator()
    self.menuCode.addAction(self.actionInset_Template)
    self.menuCode.addSeparator()
    self.menuCode.addAction(self.actionComment)
    self.menuCode.addAction(self.actionUncomment)
    self.menuCode.addAction(self.actionIgnore)
    self.menuCode.addAction(self.actionUnignore)
    self.menuCode.addSeparator()
    self.menuCode.addAction(self.actionPaste_Color)
    self.menuCode.addAction(self.actionPick_Position)
    self.menubar.addAction(self.menuFile.menuAction())
    self.menubar.addAction(self.menuEdit.menuAction())
    self.menubar.addAction(self.menuCode.menuAction())
    self.menubar.addAction(self.menuSet.menuAction())
    self.menubar.addAction(self.menuPalette.menuAction())
    self.menubar.addAction(self.menuCommands.menuAction())
    self.menubar.addAction(self.menuHelp.menuAction())
    self.toolBar.addAction(self.actionNew)
    self.toolBar.addAction(self.actionOpen)
    self.toolBar.addSeparator()
    self.toolBar.addAction(self.actionSave)
    self.toolBar.addAction(self.actionSave_As)
    self.toolBar.addSeparator()
    self.toolBar.addAction(self.actionInset_Template)
    self.toolBar.addAction(self.actionCopy)
    self.toolBar.addAction(self.actionCut)
    self.toolBar.addAction(self.actionPaste)
    self.toolBar.addSeparator()
    self.toolBar.addAction(self.actionFind_Replace)
    self.toolBar.addAction(self.actionUndo)
    self.toolBar.addAction(self.actionRedo)
    self.toolBar.addSeparator()
    self.toolBar.addAction(self.actionComment)
    self.toolBar.addAction(self.actionUncomment)
    self.toolBar.addAction(self.actionIgnore)
    self.toolBar.addAction(self.actionUnignore)
    self.toolBar.addSeparator()
    self.toolBar.addAction(self.actionPreview)
    self.toolBar.addAction(self.actionRun_Normal)

    self.retranslateUi(MainWindow)
    self.sizeMultiply.setCurrentIndex(1)
    self.editor.cursorPositionChanged['int','int'].connect(MainWindow.editorCursorMoved)
    self.plotImage.released.connect(MainWindow.evaluateScriptImage)
    self.actionOpen.triggered.connect(MainWindow.fileOpen)
    self.actionSave.triggered.connect(MainWindow.fileSave)
    self.actionSave_As.triggered.connect(MainWindow.fileSaveAs)
    self.actionCopy.triggered.connect(self.editor.copy)
    self.actionCut.triggered.connect(self.editor.cut)
    self.actionPaste.triggered.connect(self.editor.paste)
    self.actionIgnore.triggered.connect(MainWindow.ignoreSelection)
    self.actionUnignore.triggered.connect(MainWindow.unignoreSelection)
    self.applySize.released.connect(MainWindow.evaluateScript)
    self.scaling.returnPressed.connect(MainWindow.displayPixmaps)
    self.scaleToFit.released.connect(MainWindow.displayPixmaps)
    self.actionRun_Normal.triggered.connect(MainWindow.evaluateScriptImage)
    self.actionPreview.triggered.connect(MainWindow.evaluateScript)
    self.actionPaste_Color.triggered.connect(MainWindow.pasteColor)
    self.actionComment.triggered.connect(MainWindow.commentSelection)
    self.actionUncomment.triggered.connect(MainWindow.uncommentSelection)
    self.actionUndo.triggered.connect(self.editor.undo)
    self.actionRedo.triggered.connect(self.editor.redo)
    self.actionNew.triggered.connect(MainWindow.newDocument)
    self.actionPick_Position.triggered.connect(MainWindow.pickPosition)
    self.actionGnuplot_Help.triggered.connect(MainWindow.gnuplotHelp)
    self.actionAbout.triggered.connect(MainWindow.aboutDialog)
    self.applyFont.released.connect(MainWindow.evaluateScript)
    self.sizeMultiply.currentIndexChanged['QString'].connect(MainWindow.evaluateScript)
    self.actionAdd_Line_at_Cursor.triggered.connect(MainWindow.addMacro)
    self.actionDeleteMacro.triggered.connect(MainWindow.deleteMacro)
    self.encoding.currentIndexChanged['QString'].connect(MainWindow.changeEncoding)
    self.filenameList.fileDoubleClicked['QString'].connect(self.editor.insert)
    self.actionInset_Template.triggered.connect(MainWindow.insertTemplate)
    self.editor.modificationChanged['bool'].connect(MainWindow.textModified)
    self.filterEntry.returnPressed.connect(MainWindow.changeFilelistFilters)
    self.actionQuit.triggered.connect(MainWindow.close)
    self.actionFind_Replace.triggered.connect(MainWindow.openSearchDialog)
    self.actionWrap_Lines.triggered.connect(MainWindow.toggleWrapMode)
    self.actionPrint.triggered.connect(MainWindow.openPrintDialog)
    QtCore.QMetaObject.connectSlotsByName(MainWindow)

  def retranslateUi(self, MainWindow):
    _translate = QtCore.QCoreApplication.translate
    MainWindow.setWindowTitle(_translate("MainWindow", "Gnuplot Editor"))
    self.autoPreview.setText(_translate("MainWindow", "Automatic Preview"))
    self.label_3.setText(_translate("MainWindow", "Document Encoding"))
    self.encoding.setItemText(0, _translate("MainWindow", "utf8"))
    self.encoding.setItemText(1, _translate("MainWindow", "iso_8859_1"))
    self.encoding.setItemText(2, _translate("MainWindow", "iso_8859_2"))
    self.encoding.setItemText(3, _translate("MainWindow", "iso_8859_9"))
    self.encoding.setItemText(4, _translate("MainWindow", "iso_8859_15"))
    self.encoding.setItemText(5, _translate("MainWindow", "cp437"))
    self.encoding.setItemText(6, _translate("MainWindow", "cp850"))
    self.encoding.setItemText(7, _translate("MainWindow", "cp852"))
    self.encoding.setItemText(8, _translate("MainWindow", "cp950"))
    self.encoding.setItemText(9, _translate("MainWindow", "cp1250"))
    self.encoding.setItemText(10, _translate("MainWindow", "cp1251"))
    self.encoding.setItemText(11, _translate("MainWindow", "cp1254"))
    self.label_4.setText(_translate("MainWindow", "Apply to preview:"))
    self.applySize.setText(_translate("MainWindow", "Size"))
    self.sizeMultiply.setItemText(0, _translate("MainWindow", "x1"))
    self.sizeMultiply.setItemText(1, _translate("MainWindow", "x½"))
    self.sizeMultiply.setItemText(2, _translate("MainWindow", "x¼"))
    self.applyFont.setText(_translate("MainWindow", "Font"))
    self.plotImage.setText(_translate("MainWindow", "Run Script"))
    self.menuFile.setTitle(_translate("MainWindow", "File"))
    self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
    self.menuHelp.setTitle(_translate("MainWindow", "Help"))
    self.menuCommands.setTitle(_translate("MainWindow", "&User Macros"))
    self.menuSet.setTitle(_translate("MainWindow", "Set"))
    self.menuPalette.setTitle(_translate("MainWindow", "Palette"))
    self.menuCode.setTitle(_translate("MainWindow", "S&cript"))
    self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
    self.dockWidget.setWindowTitle(_translate("MainWindow", "&Gnuplot Output"))
    self.dockWidget_2.setWindowTitle(_translate("MainWindow", "G&nuplot Input"))
    self.dockWidget_3.setWindowTitle(_translate("MainWindow", "&Data Files"))
    self.label_5.setText(_translate("MainWindow", "Filters:"))
    self.dockWidget_4.setWindowTitle(_translate("MainWindow", "&Images"))
    self.fileName.setPlaceholderText(_translate("MainWindow", "Image File Name"))
    self.label_2.setText(_translate("MainWindow", "Scale:"))
    self.scaling.setText(_translate("MainWindow", "100"))
    self.label.setText(_translate("MainWindow", "%"))
    self.scaleToFit.setText(_translate("MainWindow", "Fit"))
    self.actionOpen.setText(_translate("MainWindow", "&Open..."))
    self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
    self.actionSave.setText(_translate("MainWindow", "&Save"))
    self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
    self.actionSave_As.setText(_translate("MainWindow", "Sa&ve As..."))
    self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
    self.actionCopy.setText(_translate("MainWindow", "&Copy"))
    self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
    self.actionCut.setText(_translate("MainWindow", "Cut"))
    self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X"))
    self.actionPaste.setText(_translate("MainWindow", "&Paste"))
    self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
    self.actionComment.setText(_translate("MainWindow", "&Comment"))
    self.actionComment.setShortcut(_translate("MainWindow", "Ctrl+M"))
    self.actionUncomment.setText(_translate("MainWindow", "&Uncomment"))
    self.actionUncomment.setShortcut(_translate("MainWindow", "Ctrl+Shift+M"))
    self.actionPaste_Color.setText(_translate("MainWindow", "&Paste Color..."))
    self.actionIgnore.setText(_translate("MainWindow", "I&gnore"))
    self.actionIgnore.setShortcut(_translate("MainWindow", "Ctrl+I"))
    self.actionUnignore.setText(_translate("MainWindow", "U&nignore"))
    self.actionUnignore.setShortcut(_translate("MainWindow", "Ctrl+Shift+I"))
    self.actionPreview.setText(_translate("MainWindow", "&Run Preview"))
    self.actionPreview.setToolTip(_translate("MainWindow", "Run script but remove output and terminal command (no image is created)"))
    self.actionPreview.setShortcut(_translate("MainWindow", "Ctrl+Return"))
    self.actionRun_Normal.setText(_translate("MainWindow", "Run &Script"))
    self.actionRun_Normal.setToolTip(_translate("MainWindow", "Run script without alterations"))
    self.actionRun_Normal.setShortcut(_translate("MainWindow", "Ctrl+Shift+Return"))
    self.actionUndo.setText(_translate("MainWindow", "&Undo"))
    self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
    self.actionRedo.setText(_translate("MainWindow", "&Redo"))
    self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
    self.actionNew.setText(_translate("MainWindow", "&New"))
    self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
    self.actionPick_Position.setText(_translate("MainWindow", "Pic&k Position..."))
    self.actionGnuplot_Help.setText(_translate("MainWindow", "&Gnuplot Help..."))
    self.actionAbout.setText(_translate("MainWindow", "&About..."))
    self.actionAdd_Line_at_Cursor.setText(_translate("MainWindow", "&Add Line at Cursor"))
    self.actionDeleteMacro.setText(_translate("MainWindow", "&Delete Macro..."))
    self.actionInset_Template.setText(_translate("MainWindow", "&Inset Template"))
    self.actionQuit.setText(_translate("MainWindow", "&Quit"))
    self.actionFind_Replace.setText(_translate("MainWindow", "&Find/Replace..."))
    self.actionFind_Replace.setShortcut(_translate("MainWindow", "Ctrl+F"))
    self.actionWrap_Lines.setText(_translate("MainWindow", "&Wrap Lines"))
    self.actionWrap_Lines.setShortcut(_translate("MainWindow", "F10"))
    self.actionPrint.setText(_translate("MainWindow", "&Print"))
    self.actionPrint.setShortcut(_translate("MainWindow", "Ctrl+P"))

from PyQt5 import Qsci
from .dirlist_widget import DirListWidget
from . import icons_rc
