# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/search_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
  def setupUi(self, Dialog):
    Dialog.setObjectName("Dialog")
    Dialog.resize(373, 153)
    self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
    self.verticalLayout.setObjectName("verticalLayout")
    self.gridLayout_2 = QtWidgets.QGridLayout()
    self.gridLayout_2.setObjectName("gridLayout_2")
    self.replaceEntry = QtWidgets.QLineEdit(Dialog)
    self.replaceEntry.setObjectName("replaceEntry")
    self.gridLayout_2.addWidget(self.replaceEntry, 1, 1, 1, 1)
    self.label_2 = QtWidgets.QLabel(Dialog)
    self.label_2.setObjectName("label_2")
    self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
    self.findEntry = QtWidgets.QLineEdit(Dialog)
    self.findEntry.setObjectName("findEntry")
    self.gridLayout_2.addWidget(self.findEntry, 0, 1, 1, 1)
    self.label = QtWidgets.QLabel(Dialog)
    self.label.setObjectName("label")
    self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
    self.verticalLayout.addLayout(self.gridLayout_2)
    self.gridLayout = QtWidgets.QGridLayout()
    self.gridLayout.setObjectName("gridLayout")
    self.findMatchWord = QtWidgets.QCheckBox(Dialog)
    self.findMatchWord.setObjectName("findMatchWord")
    self.gridLayout.addWidget(self.findMatchWord, 0, 1, 1, 1)
    self.findRegex = QtWidgets.QCheckBox(Dialog)
    self.findRegex.setObjectName("findRegex")
    self.gridLayout.addWidget(self.findRegex, 0, 0, 1, 1)
    self.findForward = QtWidgets.QCheckBox(Dialog)
    self.findForward.setChecked(True)
    self.findForward.setObjectName("findForward")
    self.gridLayout.addWidget(self.findForward, 1, 1, 1, 1)
    self.findCaseSensitive = QtWidgets.QCheckBox(Dialog)
    self.findCaseSensitive.setChecked(True)
    self.findCaseSensitive.setObjectName("findCaseSensitive")
    self.gridLayout.addWidget(self.findCaseSensitive, 1, 0, 1, 1)
    self.verticalLayout.addLayout(self.gridLayout)
    spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.verticalLayout.addItem(spacerItem)
    self.horizontalLayout = QtWidgets.QHBoxLayout()
    self.horizontalLayout.setObjectName("horizontalLayout")
    self.findButton = QtWidgets.QPushButton(Dialog)
    self.findButton.setObjectName("findButton")
    self.horizontalLayout.addWidget(self.findButton)
    self.replaceButton = QtWidgets.QPushButton(Dialog)
    self.replaceButton.setObjectName("replaceButton")
    self.horizontalLayout.addWidget(self.replaceButton)
    self.replaceAllButton = QtWidgets.QPushButton(Dialog)
    self.replaceAllButton.setObjectName("replaceAllButton")
    self.horizontalLayout.addWidget(self.replaceAllButton)
    self.cancelButton = QtWidgets.QPushButton(Dialog)
    self.cancelButton.setObjectName("cancelButton")
    self.horizontalLayout.addWidget(self.cancelButton)
    self.verticalLayout.addLayout(self.horizontalLayout)

    self.retranslateUi(Dialog)
    self.findButton.clicked.connect(Dialog.find)
    self.replaceButton.clicked.connect(Dialog.replace)
    self.replaceAllButton.clicked.connect(Dialog.replaceAll)
    self.cancelButton.clicked.connect(Dialog.deleteLater)
    QtCore.QMetaObject.connectSlotsByName(Dialog)
    Dialog.setTabOrder(self.findEntry, self.replaceEntry)
    Dialog.setTabOrder(self.replaceEntry, self.findButton)
    Dialog.setTabOrder(self.findButton, self.replaceButton)
    Dialog.setTabOrder(self.replaceButton, self.replaceAllButton)
    Dialog.setTabOrder(self.replaceAllButton, self.cancelButton)
    Dialog.setTabOrder(self.cancelButton, self.findRegex)
    Dialog.setTabOrder(self.findRegex, self.findCaseSensitive)
    Dialog.setTabOrder(self.findCaseSensitive, self.findMatchWord)
    Dialog.setTabOrder(self.findMatchWord, self.findForward)

  def retranslateUi(self, Dialog):
    _translate = QtCore.QCoreApplication.translate
    Dialog.setWindowTitle(_translate("Dialog", "Gnuplot Editor - Find/Replace"))
    self.label_2.setText(_translate("Dialog", "Replace:"))
    self.label.setText(_translate("Dialog", "Find:"))
    self.findMatchWord.setText(_translate("Dialog", "Match only Whole Word"))
    self.findRegex.setText(_translate("Dialog", "Regular Expression"))
    self.findForward.setText(_translate("Dialog", "Forward"))
    self.findCaseSensitive.setText(_translate("Dialog", "Case Sensitive"))
    self.findButton.setText(_translate("Dialog", "Find"))
    self.replaceButton.setText(_translate("Dialog", "Replace"))
    self.replaceAllButton.setText(_translate("Dialog", "Replace All"))
    self.cancelButton.setText(_translate("Dialog", "Cancel"))

